on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/**
env:
  ACR_NAME: testdemoacr01
  STORE_APP: frontendaca009
  DOCKERFILE: src/Store/Dockerfile
  INVENTORY_APP: inventoryapiapp008
  PRODUCT_APP: productapiapp007
  RG: RG04
  ENVIRONMENT: env-apiapp03
  
name: Building images and resources

jobs:
  resource-build:
    # name: Building container and provisioning Azure Resources
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run AzureCLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          # az extension add --name containerapp --upgrade
          # az provider register --namespace Microsoft.App
          # az provider register --namespace Microsoft.OperationalInsights
          chmod +x $GITHUB_WORKSPACE/azure-deploy.sh
          echo "Running the deployment script"
          $GITHUB_WORKSPACE/azure-deploy.sh

  build-storeimage:
    runs-on: ubuntu-latest
    needs: resource-build

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run AzureCLI script
      uses: azure/CLI@v1
      # env:
      #   ACR_NAME: testdemoacr01
      #   STORE_APP: frontendaca009
      #   DOCKERFILE: src/Store/Dockerfile
      with:
        azcliversion: 2.52.0
        inlineScript: |
          echo "Build container image and push to ACR"
          az acr build --registry $ACR_NAME --image $STORE_APP -f $GITHUB_WORKSPACE/$DOCKERFILE ./src/

  build-inventoryimage:
    runs-on: ubuntu-latest
    needs: resource-build

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
          echo "Build container image and push to ACR"
          az acr build --registry $ACR_NAME --image $INVENTORY_APP -f $GITHUB_WORKSPACE/src/Store.InventoryApi/Dockerfile ./src/

  build-productimage:
    runs-on: ubuntu-latest
    needs: resource-build

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
          echo "Build container image and push to ACR"
          az acr build --registry $ACR_NAME --image $PRODUCT_APP -f $GITHUB_WORKSPACE/src/Store.ProductApi/Dockerfile ./src/

  Deploy_images:
    runs-on: ubuntu-latest
    needs: [build-storeimage, build-inventoryimage, build-productimage]
    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy INVENTORY_APP
      if: always()
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
          echo "Updating container app with ACR image"
          az containerapp update -n $INVENTORY_APP -g $RG -i $ACR_NAME.azurecr.io/$INVENTORY_APP:latest
          # az containerapp up \
          # --name $INVENTORY_APP \
          # --image testdemoacr01.azurecr.io/$INVENTORY_APP:latest \
          # --resource-group $RG \
          # --environment $ENVIRONMENT \
          # --ingress internal \
          # --target-port 80

    - name: Deploy PRODUCT_APP
      if: always()
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
          echo "Updating container app with ACR image"
          az containerapp update -n $PRODUCT_APP -g $RG -i $ACR_NAME.azurecr.io/$PRODUCT_APP:latest
          
          # az containerapp up \
          # --name $PRODUCT_APP \
          # --image testdemoacr01.azurecr.io/$PRODUCT_APP:latest \
          # --resource-group $RG \
          # --environment $ENVIRONMENT \
          # --ingress internal \
          # --target-port 80

    - name: deploy store container
      if: always()
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: testdemoacr01.azurecr.io/$STORE_APP:latest
        containerAppName: $STORE_APP
        containerAppEnvironment: $ENVIRONMENT
        resourceGroup: $RG
        environmentVariables: |
          'ProductsApi=http://$PRODUCT_APP' 'InventoryApi=http://$INVENTORY_APP' 'ASPNETCORE_ENVIRONMENT=Development'
